### ISSUE TITLE
run this demo

### ISSUE THREAD

**Issue by wanghaisheng** [smart-on-fhir/SoF-MedList#1]
when i try to run this demo, in the  step " approval required for my app", scroller does not work well,i could not see the authorize and deny button.
should i  replace settings in AppDelegate.swift

```
        settings: [
            "client_id": "my_mobile_app",
            "redirect": "smartapp://callback",
        ]
```

**Comment by p2** [comment]
Seems to work for me by scrolling down, does that not work for you? No, the settings are correct.

![screen shot 2015-04-23 at 12 48 46](https://cloud.githubusercontent.com/assets/358485/7302404/335042bc-e9b7-11e4-8914-656c58a25548.png)

**Comment by wanghaisheng** [comment]
i have tried all my simulator,wont work.xcode Version 6.3 (6D570)

**Comment by p2** [comment]
I'm on 6.3.1 (6D1002), works fine? What exactly is not working for you? Can you not scroll the web view with click-drag?

**Comment by wanghaisheng** [comment]
whenever i  scroll ,i only can see the top of "remember this decision",i could not see anything under it

**Comment by p2** [comment]
Sounds like your simulator is larger than your Mac's screen and cut off at the bottom. Try pressing <key>CMD</key> + <key>3</key> or use the mouse's scroll wheel.

**Comment by wanghaisheng** [comment]
fix
