### ISSUE TITLE
Problem With CocoaPods?

### ISSUE THREAD

**Issue by mashype** [smart-on-fhir/SoF-MedList#6]
I am trying to import via CocoaPods and keep getting an error that XCode is unable to find a module named "SMART". Is there anything special that needs to be done other than the pod init, put the 'pod 'SMART'' in the podfile and install, then open as the workspace? I have not been having any luck trying to figure out the OAUTH setup for this and was hoping this would help

**Comment by p2** [comment]
There is no need to use CocoaPods with this project, it's already set up. Follow the [instructions](https://github.com/smart-on-fhir/SoF-Demo#installation), especially the `--recursive` part, and you're good to go.

**Comment by mashype** [comment]
Thanks. I was just downloading the zip file, so I will try it with the direct clone.
